# Auto-generated by Backstage scaffolder for ${{ values.name }}
project_name    = "${{ values.name }}"
environment     = "dev"
location        = "southeastasia"
subscription_id = "" # Set via pipeline variable
owner_team      = "${{ values.owner }}"
app_service_sku = "B1"
include_database = ${{ values.includeDatabase }}
include_redis    = ${{ values.includeRedis }}
db_password      = "" # Set via pipeline secret
