# =============================================================================
# Terraform Remote State — Azure Blob Storage
# =============================================================================
# Generated by MP-Backstage Scaffolder
# API: ${{ values.apiDisplayName }}
#
# State file path: ${{ values.tfStateResourceGroup }}/${{ values.tfStateStorageAccount }}/tfstate/${{ values.apiName }}.terraform.tfstate
#
# หมายเหตุ: backend block ไม่รองรับ variable — ค่าต่างๆ ถูก inject
#           ตอน scaffold โดย Backstage (ไม่ใช่ตอน terraform init)
# =============================================================================

terraform {
  required_version = ">= 1.3.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  backend "azurerm" {
    resource_group_name  = "${{ values.tfStateResourceGroup }}"
    storage_account_name = "${{ values.tfStateStorageAccount }}"
    container_name       = "state"
    key                  = "${{ values.apiName }}.terraform.tfstate"
    use_azuread_auth     = true
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true  # service principal ไม่ต้องการสิทธิ์ register/action
}
