# =============================================================================
# main.tf — APIM API Registration, Product Assignment, Backend, Named Values
# =============================================================================
# Generated by MP-Backstage Scaffolder
# API: ${{ values.apiDisplayName }} (v${{ values.apiVersion }})
#
# ADR REFERENCES:
#   ADR-002 — Shift-Left API Governance (Backstage gate before deploy)
#   ADR-003 — Centralized Zero-Trust Execution via APIM
#   ADR-007 — Trusted Subsystem Two-Leg Authentication
#   ADR-012 — Tiered Traffic and Rate Limit Design
# =============================================================================

# ---------------------------------------------------------------------------
# Data Sources — อ้างอิง resources ที่มีอยู่แล้ว (APIM, Resource Group)
# ---------------------------------------------------------------------------

data "azurerm_api_management" "apim" {
  name                = var.apim_instance_name
  resource_group_name = var.resource_group_name
}

data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

# ---------------------------------------------------------------------------
# API Registration — import OpenAPI spec จากไฟล์ openapi.yaml
# ---------------------------------------------------------------------------
# ADR-002: API ถูก register ใน Backstage catalog ก่อน pipeline นี้จะรัน
#          (Backstage Gate ใน Stage 1 ตรวจสอบ)
# ---------------------------------------------------------------------------

resource "azurerm_api_management_api" "api" {
  name                = var.api_name
  resource_group_name = var.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name
  revision            = "1"
  display_name        = var.api_display_name
  path                = trimprefix(var.api_path, "/")
  protocols           = ["https"]
  service_url         = var.backend_url

  import {
    content_format = "openapi"
    # openapi.yaml อยู่ที่ root ของ repo — iac/ directory เป็น subfolder
    content_value = file("${path.module}/../openapi.yaml")
  }
}

# ---------------------------------------------------------------------------
# Product-API Assignment — ผูก API เข้ากับ Product tier (ADR-012)
# ---------------------------------------------------------------------------
# Bronze: 100 req/min | Silver: 500 req/min | Gold: Unlimited
# Product ต้อง pre-exist ใน APIM (สร้างโดย platform team ล่วงหน้า)
# ---------------------------------------------------------------------------

resource "azurerm_api_management_product_api" "tier_assignment" {
  count = var.product_tier != "" ? 1 : 0

  resource_group_name = var.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name
  product_id          = var.product_tier
  api_name            = azurerm_api_management_api.api.name
}

# ---------------------------------------------------------------------------
# Backend Service — กำหนด backend URL ที่ APIM จะ proxy requests ไป
# ---------------------------------------------------------------------------
# ADR-007: Backend connectivity ผ่าน Managed Identity token
#          (configured ใน policies.tf — authentication-managed-identity)
# ---------------------------------------------------------------------------

resource "azurerm_api_management_backend" "backend" {
  name                = "${var.api_name}-backend"
  resource_group_name = var.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name
  protocol            = "http"
  url                 = var.backend_url

  {%- if values.apiDescription %}
  description = "${{ values.apiDescription }}"
  {%- endif %}
}

# ---------------------------------------------------------------------------
# Named Values — ค่า runtime สำหรับ policy (ไม่มี secret ใน source code)
# ---------------------------------------------------------------------------

resource "azurerm_api_management_named_value" "tenant_id" {
  count               = var.tenant_id != "" ? 1 : 0
  name                = "${var.api_name}-tenant-id"
  resource_group_name = var.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name
  display_name        = "${var.api_name}-tenant-id"
  value               = var.tenant_id
  secret              = false
}

resource "azurerm_api_management_named_value" "app_id" {
  count               = var.app_id != "" ? 1 : 0
  name                = "${var.api_name}-app-id"
  resource_group_name = var.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name
  display_name        = "${var.api_name}-app-id"
  value               = var.app_id
  secret              = false
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------

output "api_gateway_url" {
  description = "APIM Gateway URL สำหรับ API นี้"
  value       = "${data.azurerm_api_management.apim.gateway_url}/${trimprefix(var.api_path, "/")}"
}

output "api_management_api_id" {
  description = "Resource ID ของ APIM API"
  value       = azurerm_api_management_api.api.id
}
