# =============================================================================
# monitoring.tf — Application Insights + APIM Diagnostic + Alert Rules
# =============================================================================
# Generated by MP-Backstage Scaffolder
# API: ${{ values.apiDisplayName }} (v${{ values.apiVersion }})
#
# ADR REFERENCES:
#   ADR-013 — Observability Strategy and Incident Triage Model
#
# TRIAGE TIERS (ADR-013):
#   Tier 1 (IAM):      401/403 auth failures  → IAM Team
#   Tier 2 (Platform):  429/503 rate limiting  → Platform/APIM Team
#   Tier 3 (Backend):   5xx errors             → Backend Dev Team
#
# หมายเหตุ: Alert rules สร้างโดย count = 1 เสมอ
#           แต่ถ้า action_group_id ว่าง notification จะไม่ถูกส่ง
#           → ใส่ Resource ID จริงใน terraform.tfvars เพื่อเปิด notification
# =============================================================================

# ---------------------------------------------------------------------------
# Application Insights — telemetry sink สำหรับ API นี้โดยเฉพาะ
# ---------------------------------------------------------------------------

locals {
  monitoring_enabled = var.log_analytics_workspace_id != "" ? true : false
}

resource "azurerm_application_insights" "api" {
  count = local.monitoring_enabled ? 1 : 0
  name                = "ai-${{ values.apiName }}"
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = var.resource_group_name
  application_type    = "web"
  workspace_id        = var.log_analytics_workspace_id != "" ? var.log_analytics_workspace_id : null
  retention_in_days   = 90

  tags = {
    environment = "production"
    managed_by  = "terraform"
    api         = "${{ values.apiName }}"
    owner       = "${{ values.buName }}"
    backstage   = "${{ values.backstageBaseUrl }}/catalog/default/component/${{ values.apiName }}"
  }
}

# ---------------------------------------------------------------------------
# APIM Logger — เชื่อม Application Insights กับ APIM instance
# ---------------------------------------------------------------------------

resource "azurerm_api_management_logger" "app_insights" {
  count = local.monitoring_enabled ? 1 : 0
  name                = "ai-logger-${{ values.apiName }}"
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = var.resource_group_name

  application_insights {
    instrumentation_key = azurerm_application_insights.api[0].instrumentation_key
  }
}

# ---------------------------------------------------------------------------
# NOTE: azurerm_api_management_diagnostic และ azurerm_monitor_diagnostic_setting
# เป็น APIM instance-level resources — มีได้แค่อันเดียวต่อ APIM instance
# ควรให้ platform team จัดการแยกต่างหาก ไม่ใช่สร้างใหม่ทุก API
# ---------------------------------------------------------------------------

# ===========================================================================
# ALERT 1: 5xx Error Spike → Backend Dev Team (Tier 3)
# ADR-013: Sev1 — Backend team รับผิดชอบ 5xx errors
# ===========================================================================

resource "azurerm_monitor_scheduled_query_rules_alert_v2" "error_5xx_spike" {
  count = local.monitoring_enabled ? 1 : 0
  name                = "alert-5xx-${{ values.apiName }}"
  resource_group_name = var.resource_group_name
  location            = data.azurerm_resource_group.rg.location

  display_name = "5xx Error Spike — ${{ values.apiDisplayName }}"
  description  = "ADR-013 Tier 3 (Backend): 5xx error rate เกิน 5% ใน 5 นาที — Route ไป Backend Dev team"

  evaluation_frequency = "PT5M"
  window_duration      = "PT5M"
  severity             = 1
  enabled              = true

  scopes = [var.log_analytics_workspace_id]

  criteria {
    query = <<-KQL
      ApiManagementGatewayLogs
      | where TimeGenerated > ago(5m)
      | where ApiId == "${{ values.apiName }}"
      | summarize
          TotalRequests = count(),
          Count5xx      = countif(ResponseCode >= 500 and ResponseCode < 600)
      | extend Rate5xx = 100.0 * Count5xx / TotalRequests
      | where Rate5xx > 5
    KQL

    time_aggregation_method = "Count"
    operator                = "GreaterThan"
    threshold               = 0

    failing_periods {
      minimum_failing_periods_to_trigger_alert = 1
      number_of_evaluation_periods             = 1
    }
  }

  action {
    action_groups = var.backend_dev_action_group_id != "" ? [var.backend_dev_action_group_id] : []

    custom_properties = {
      "backstage_component" = "${{ values.backstageBaseUrl }}/catalog/default/component/${{ values.apiName }}"
      "triage_tier"         = "Tier 3: Backend"
      "adr_reference"       = "ADR-013"
      "alert_type"          = "5xx-error-spike"
      "api_id"              = "${{ values.apiName }}"
    }
  }

  tags = {
    environment   = "production"
    managed_by    = "terraform"
    triage_tier   = "tier-3-backend"
    adr_reference = "ADR-013"
    api           = "${{ values.apiName }}"
  }
}

# ===========================================================================
# ALERT 2: 401/403 Auth Failure Spike → IAM Team (Tier 1)
# ADR-013: Sev2 — IAM team รับผิดชอบ authentication/authorization failures
# ===========================================================================

resource "azurerm_monitor_scheduled_query_rules_alert_v2" "auth_failure_spike" {
  count = local.monitoring_enabled ? 1 : 0
  name                = "alert-auth-${{ values.apiName }}"
  resource_group_name = var.resource_group_name
  location            = data.azurerm_resource_group.rg.location

  display_name = "401/403 Auth Failure Spike — ${{ values.apiDisplayName }}"
  description  = "ADR-013 Tier 1 (IAM): Auth failures เกิน 10 ครั้ง ใน 5 นาที — Route ไป IAM team"

  evaluation_frequency = "PT5M"
  window_duration      = "PT5M"
  severity             = 2
  enabled              = true

  scopes = [var.log_analytics_workspace_id]

  criteria {
    query = <<-KQL
      ApiManagementGatewayLogs
      | where TimeGenerated > ago(5m)
      | where ApiId == "${{ values.apiName }}"
      | where ResponseCode == 401 or ResponseCode == 403
      | summarize AuthFailureCount = count()
      | where AuthFailureCount > 10
    KQL

    time_aggregation_method = "Count"
    operator                = "GreaterThan"
    threshold               = 0

    failing_periods {
      minimum_failing_periods_to_trigger_alert = 1
      number_of_evaluation_periods             = 1
    }
  }

  action {
    action_groups = var.iam_action_group_id != "" ? [var.iam_action_group_id] : []

    custom_properties = {
      "backstage_component" = "${{ values.backstageBaseUrl }}/catalog/default/component/${{ values.apiName }}"
      "triage_tier"         = "Tier 1: IAM"
      "adr_reference"       = "ADR-013"
      "alert_type"          = "auth-failure-spike"
      "api_id"              = "${{ values.apiName }}"
    }
  }

  tags = {
    environment   = "production"
    managed_by    = "terraform"
    triage_tier   = "tier-1-iam"
    adr_reference = "ADR-013"
    api           = "${{ values.apiName }}"
  }
}

# ===========================================================================
# ALERT 3: 429/503 Rate Limit Spike → Platform/APIM Team (Tier 2)
# ADR-013: Sev2 — Platform team รับผิดชอบ rate limiting และ availability
# ===========================================================================

resource "azurerm_monitor_scheduled_query_rules_alert_v2" "rate_limit_spike" {
  count = local.monitoring_enabled ? 1 : 0
  name                = "alert-ratelimit-${{ values.apiName }}"
  resource_group_name = var.resource_group_name
  location            = data.azurerm_resource_group.rg.location

  display_name = "429/503 Rate Limit Spike — ${{ values.apiDisplayName }}"
  description  = "ADR-013 Tier 2 (Platform): Rate limit events เกิน 10 ครั้ง ใน 5 นาที — Route ไป Platform team"

  evaluation_frequency = "PT5M"
  window_duration      = "PT5M"
  severity             = 2
  enabled              = true

  scopes = [var.log_analytics_workspace_id]

  criteria {
    query = <<-KQL
      ApiManagementGatewayLogs
      | where TimeGenerated > ago(5m)
      | where ApiId == "${{ values.apiName }}"
      | where ResponseCode == 429 or ResponseCode == 503
      | summarize RateLimitCount = count()
      | where RateLimitCount > 10
    KQL

    time_aggregation_method = "Count"
    operator                = "GreaterThan"
    threshold               = 0

    failing_periods {
      minimum_failing_periods_to_trigger_alert = 1
      number_of_evaluation_periods             = 1
    }
  }

  action {
    action_groups = var.platform_action_group_id != "" ? [var.platform_action_group_id] : []

    custom_properties = {
      "backstage_component" = "${{ values.backstageBaseUrl }}/catalog/default/component/${{ values.apiName }}"
      "triage_tier"         = "Tier 2: Platform"
      "adr_reference"       = "ADR-013"
      "alert_type"          = "rate-limit-spike"
      "api_id"              = "${{ values.apiName }}"
    }
  }

  tags = {
    environment   = "production"
    managed_by    = "terraform"
    triage_tier   = "tier-2-platform"
    adr_reference = "ADR-013"
    api           = "${{ values.apiName }}"
  }
}

# ---------------------------------------------------------------------------
# Outputs — Observability
# ---------------------------------------------------------------------------

output "app_insights_instrumentation_key" {
  description = "Instrumentation key สำหรับ Application Insights"
  value       = local.monitoring_enabled ? azurerm_application_insights.api[0].instrumentation_key : ""
  sensitive   = true
}

output "app_insights_connection_string" {
  description = "Connection string สำหรับ Application Insights"
  value       = local.monitoring_enabled ? azurerm_application_insights.api[0].connection_string : ""
  sensitive   = true
}

output "app_insights_app_id" {
  description = "Application ID สำหรับใช้ใน KQL queries"
  value       = local.monitoring_enabled ? azurerm_application_insights.api[0].app_id : ""
}
