# =============================================================================
# policies.tf — APIM API Policy (inline จาก policy.xml)
# =============================================================================
# Generated by MP-Backstage Scaffolder
# API: ${{ values.apiDisplayName }}
#
# ADR REFERENCES:
#   ADR-004 — Policy-as-Code with Fragment Library
#   ADR-006 — Domain-Based API Authorization
#   ADR-013 — Observability Strategy (Correlation ID injection)
#
# NOTE: ใช้ policy.xml inline (ไม่ใช่ policy fragment)
#       เมื่อ platform มี Fragment Library พร้อมแล้วให้เปลี่ยนมาใช้
#       <include-fragment fragment-id="JWT-Validation-Internal" />
# =============================================================================

resource "azurerm_api_management_api_policy" "api_policy" {
  api_name            = azurerm_api_management_api.api.name
  resource_group_name = var.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name

  # policy.xml อยู่ที่ root ของ repo — iac/ directory เป็น subfolder
  xml_content = file("${path.module}/../policy.xml")
}
